# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_fulfillment}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Cody Fauser", "James MacAulay"]
  s.date = %q{2010-12-13}
  s.email = %q{cody@shopify.com}

  s.files       = Dir.glob("{lib}/**/*") + %w(VERSION CHANGELOG)
  s.test_files  = Dir.glob("{test}/**/*")

  s.homepage = %q{http://github.com/shopify/active_fulfillment}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Framework and tools for dealing with shipping, tracking and order fulfillment services.}

  s.add_dependency('activesupport', '~> 3.2.9')
  s.add_dependency('builder', '>= 2.0.0')
  s.add_dependency('active_utils', '>= 1.0.1')

  s.add_development_dependency('rake')
  s.add_development_dependency('mocha')
  s.add_development_dependency('rdoc', '>= 2.4.2')
end

